spring:
  datasource:
    url: jdbc:h2:mem:sms
    username: anupam
    password: anupam
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    #defer-datasource-initialization: true

  h2:
    console.enabled: true
  sql:
    init.mode: always