spring:
  datasource:
    url: jdbc:h2:mem:sms
    username: anupam
    password: anupam
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    #defer-datasource-initialization: true

  h2:
    console.enabled: true
    console.settings.web-allow-others: true

  sql:
    init.mode: never
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:
token:
  key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351